openapi: 3.0.3
info:
  title: Library API - OpenAPI 3.0
  termsOfService: http://swagger.io/terms/
  contact:
    email: boottechnologies.ci@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: '1.0.11'
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8080/api/v1
    description: Development server
  - url: http://localhost:8081/api/v1
    description: Staging server
  - url: http://localhost:8082/api/v1
    description: Production server
tags:
  - name: Test
    description: Operations about test
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /test:
    get:
      tags:
        - Test
      summary: Test summary
      operationId: getTest
      responses:
        '200':
          description: return successfully
          content:
            text/plain:
              schema:
                type: string
        '401':
          description: You are not authorized to view the resource
        '403':
          description: Accessing the resource you were trying to reach is forbidden
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT